branch-defaults:
  master:
    environment: null
global:
  application_name: twodice
  default_ec2_keyname: aws-email
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
